on:
  push:
    branches: 
      - main


jobs:
  build_webpack:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build webpack
        run: |
          npm install
          npx webpack 

  check_changes:
      needs: build_webpack
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Check if avina.css or avina.js was changed
          uses: tj-actions/verify-changed-files@v13
          id: verify-changed-files
          with:
            files: |
              **/avina.js
              **/avina.css
           
        - name: Add and Commit changes to main branch
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add ./dist/
            git commit -m 'Updates compiled Webpack files'
          if: steps.verify-changed-files.outputs.files_changed == 'true'
        - name: Push changes
          uses: ad-m/github-push-action@master
 
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
          if: steps.verify-changed-files.outputs.files_changed == 'true'
 
 
  publish-npm:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Check if package.json was changed
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
            **/package.json

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        if: steps.verify-changed-files.outputs.files_changed == 'true'

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
          if: steps.verify-changed-files.outputs.files_changed == 'true'

          
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
          if: steps.verify-changed-files.outputs.files_changed == 'true'




      # - name: Compile CSS from SCSS files
      #   uses: gha-utilities/sass-build@v0.4.11
      #   with:
      #     source: scss/main.scss
      #     destination: css/main.css

      # - name: Check if main.css was changed
      #   uses: mudlabs/simple-diff@v1.2.0
      #   id: diff
      #   with:
      #     path: css/main.css
      #     -run: exit 1
      #     if: steps.diff.outputs.modified         # Outputs: "Changed files: new.txt test_directory/new.txt"
        # - uses: actions/checkout@v2
        # - name: Check if avina.css was changed
        #   uses: mudlabs/simple-diff@v1.2.0
        #   id: css
        #   with:
        #     path: dist/avina.css
        #     -run: exit 1
        #     if: steps.diff.outputs.removed 
        # - name: Check if avina.js was changed
        #   uses: mudlabs/simple-diff@v1.2.0
        #   id: js
        #   with:
        #     path: 'dist/avina.js'
        #     -run: exit 1
  